"""empty message

Revision ID: 8c46dea9d5bc
Revises: 4635257ccd07
Create Date: 2021-12-28 21:34:20.200598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c46dea9d5bc'
down_revision = '4635257ccd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead', 'first_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('lead', 'last_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('lead', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('lead', 'city',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('lead', 'state',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('lead', 'zip',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('lead', 'owner_occupied',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('lead', 'property_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('lead', 'mls_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('lead', 'template_sent',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('lead', 'motivation_level',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead', 'motivation_level',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('lead', 'template_sent',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('lead', 'mls_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('lead', 'property_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('lead', 'owner_occupied',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('lead', 'zip',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('lead', 'state',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('lead', 'city',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('lead', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('lead', 'last_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('lead', 'first_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
