"""empty message

Revision ID: 4635257ccd07
Revises: aa87b1007196
Create Date: 2021-12-28 21:32:29.556390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4635257ccd07'
down_revision = 'aa87b1007196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead', 'phone_number',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('lead', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('lead', 'phone_number',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
