"""added text_left to users

Revision ID: bab36b405cce
Revises: ca47f9909beb
Create Date: 2022-04-29 17:01:59.002737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bab36b405cce'
down_revision = 'ca47f9909beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column('texts_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", sa.Column('texts_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
