"""separating the addresses out of the lead table

Revision ID: 65e5d37c095a
Revises: bab36b405cce
Create Date: 2022-05-31 17:26:46.320575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e5d37c095a'
down_revision = 'bab36b405cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('zip', sa.String(length=200), nullable=True),
    sa.Column('owner_occupied', sa.String(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_addresses',
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('address.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address.id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
