"""made User.name unique because there are only 2 users to start

Revision ID: 1ddc3afbeecf
Revises: 8feaaf9d25c7
Create Date: 2022-01-29 18:20:55.111701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ddc3afbeecf'
down_revision = '8feaaf9d25c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
