"""removing unused columns

Revision ID: 6c8dcfa9dc3c
Revises: 65e5d37c095a
Create Date: 2022-07-12 17:06:32.921927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8dcfa9dc3c'
down_revision = '65e5d37c095a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'phone_number')
    op.drop_column('lead', 'property_type')
    op.drop_column('lead', 'address')
    op.drop_column('lead', 'owner_occupied')
    op.drop_column('lead', 'state')
    op.drop_column('lead', 'zip')
    op.drop_column('lead', 'city')
    op.drop_column('lead', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('lead', sa.Column('city', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('lead', sa.Column('zip', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('lead', sa.Column('state', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('lead', sa.Column('owner_occupied', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lead', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('lead', sa.Column('property_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lead', sa.Column('phone_number', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
