"""initial migration

Revision ID: 7f137eac7926
Revises: 
Create Date: 2022-01-29 20:57:33.379479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f137eac7926'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('zip', sa.String(length=200), nullable=True),
    sa.Column('owner_occupied', sa.String(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('mls_status', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('contacted', sa.Integer(), nullable=True),
    sa.Column('contact_time', sa.DateTime(), nullable=True),
    sa.Column('trace_date', sa.DateTime(), nullable=True),
    sa.Column('template_sent', sa.String(length=200), nullable=True),
    sa.Column('response', sa.String(length=2000), nullable=True),
    sa.Column('motivation_level', sa.String(length=200), nullable=True),
    sa.Column('last_trace', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=100), nullable=False),
    sa.Column('contacted', sa.Integer(), nullable=True),
    sa.Column('contact_time', sa.DateTime(), nullable=True),
    sa.Column('response', sa.String(length=200), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('phone_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile_phone', sa.String(length=20), nullable=False),
    sa.Column('contacted', sa.Integer(), nullable=True),
    sa.Column('contact_time', sa.DateTime(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile_phone')
    )
    op.create_table('email_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('contact_time', sa.DateTime(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('contact_time', sa.DateTime(), nullable=True),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phone_id'], ['phone_number.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_reply')
    op.drop_table('email_reply')
    op.drop_table('phone_number')
    op.drop_table('email')
    op.drop_table('users')
    op.drop_table('template')
    op.drop_table('lead')
    # ### end Alembic commands ###
