"""import leads and template class

Revision ID: 82f4eb73d71b
Revises: af8396510055
Create Date: 2021-07-17 13:42:17.907636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f4eb73d71b'
down_revision = 'af8396510055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=200), nullable=False),
    sa.Column('zip_code', sa.String(length=200), nullable=False),
    sa.Column('owner_occupied', sa.String(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('mls_status', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('contacted', sa.Integer(), nullable=True),
    sa.Column('contact_time', sa.DateTime(), nullable=True),
    sa.Column('template_sent', sa.String(length=200), nullable=False),
    sa.Column('response', sa.String(length=200), nullable=False),
    sa.Column('motivation_level', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template')
    op.drop_table('lead')
    # ### end Alembic commands ###
