"""initial migration

Revision ID: af8396510055
Revises: 
Create Date: 2021-07-17 12:57:17.612682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8396510055'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lead_index', table_name='lead')
    op.drop_table('lead')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('index', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.TEXT(), nullable=True),
    sa.Column('last_name', sa.TEXT(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.Column('state', sa.TEXT(), nullable=True),
    sa.Column('zip', sa.INTEGER(), nullable=True),
    sa.Column('owner_occupied', sa.TEXT(), nullable=True),
    sa.Column('property_type', sa.TEXT(), nullable=True),
    sa.Column('mls_status', sa.TEXT(), nullable=True),
    sa.Column('phone_number', sa.REAL(), nullable=True),
    sa.Column('email', sa.REAL(), nullable=True),
    sa.Column('contacted', sa.REAL(), nullable=True),
    sa.Column('contact_time', sa.REAL(), nullable=True),
    sa.Column('template_sent', sa.REAL(), nullable=True),
    sa.Column('response', sa.REAL(), nullable=True),
    sa.Column('motivation_level', sa.REAL(), nullable=True)
    )
    op.create_index('ix_lead_index', 'lead', ['index'], unique=False)
    # ### end Alembic commands ###
